/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VulnerabilityRouteImport } from './routes/vulnerability'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PersonnelRouteImport } from './routes/personnel'
import { Route as OccupancyRouteImport } from './routes/occupancy'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as FloorPlansRouteImport } from './routes/floor-plans'
import { Route as CommanderRouteImport } from './routes/commander'
import { Route as BuildingsRouteImport } from './routes/buildings'
import { Route as BuildingInputRouteImport } from './routes/building-input'
import { Route as IndexRouteImport } from './routes/index'

const VulnerabilityRoute = VulnerabilityRouteImport.update({
  id: '/vulnerability',
  path: '/vulnerability',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelRoute = PersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const OccupancyRoute = OccupancyRouteImport.update({
  id: '/occupancy',
  path: '/occupancy',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorPlansRoute = FloorPlansRouteImport.update({
  id: '/floor-plans',
  path: '/floor-plans',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderRoute = CommanderRouteImport.update({
  id: '/commander',
  path: '/commander',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsRoute = BuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingInputRoute = BuildingInputRouteImport.update({
  id: '/building-input',
  path: '/building-input',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/building-input': typeof BuildingInputRoute
  '/buildings': typeof BuildingsRoute
  '/commander': typeof CommanderRoute
  '/floor-plans': typeof FloorPlansRoute
  '/incidents': typeof IncidentsRoute
  '/occupancy': typeof OccupancyRoute
  '/personnel': typeof PersonnelRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vulnerability': typeof VulnerabilityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/building-input': typeof BuildingInputRoute
  '/buildings': typeof BuildingsRoute
  '/commander': typeof CommanderRoute
  '/floor-plans': typeof FloorPlansRoute
  '/incidents': typeof IncidentsRoute
  '/occupancy': typeof OccupancyRoute
  '/personnel': typeof PersonnelRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vulnerability': typeof VulnerabilityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/building-input': typeof BuildingInputRoute
  '/buildings': typeof BuildingsRoute
  '/commander': typeof CommanderRoute
  '/floor-plans': typeof FloorPlansRoute
  '/incidents': typeof IncidentsRoute
  '/occupancy': typeof OccupancyRoute
  '/personnel': typeof PersonnelRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vulnerability': typeof VulnerabilityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/building-input'
    | '/buildings'
    | '/commander'
    | '/floor-plans'
    | '/incidents'
    | '/occupancy'
    | '/personnel'
    | '/reports'
    | '/settings'
    | '/vulnerability'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/building-input'
    | '/buildings'
    | '/commander'
    | '/floor-plans'
    | '/incidents'
    | '/occupancy'
    | '/personnel'
    | '/reports'
    | '/settings'
    | '/vulnerability'
  id:
    | '__root__'
    | '/'
    | '/building-input'
    | '/buildings'
    | '/commander'
    | '/floor-plans'
    | '/incidents'
    | '/occupancy'
    | '/personnel'
    | '/reports'
    | '/settings'
    | '/vulnerability'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuildingInputRoute: typeof BuildingInputRoute
  BuildingsRoute: typeof BuildingsRoute
  CommanderRoute: typeof CommanderRoute
  FloorPlansRoute: typeof FloorPlansRoute
  IncidentsRoute: typeof IncidentsRoute
  OccupancyRoute: typeof OccupancyRoute
  PersonnelRoute: typeof PersonnelRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  VulnerabilityRoute: typeof VulnerabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vulnerability': {
      id: '/vulnerability'
      path: '/vulnerability'
      fullPath: '/vulnerability'
      preLoaderRoute: typeof VulnerabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel': {
      id: '/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof PersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occupancy': {
      id: '/occupancy'
      path: '/occupancy'
      fullPath: '/occupancy'
      preLoaderRoute: typeof OccupancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor-plans': {
      id: '/floor-plans'
      path: '/floor-plans'
      fullPath: '/floor-plans'
      preLoaderRoute: typeof FloorPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander': {
      id: '/commander'
      path: '/commander'
      fullPath: '/commander'
      preLoaderRoute: typeof CommanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings': {
      id: '/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof BuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/building-input': {
      id: '/building-input'
      path: '/building-input'
      fullPath: '/building-input'
      preLoaderRoute: typeof BuildingInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuildingInputRoute: BuildingInputRoute,
  BuildingsRoute: BuildingsRoute,
  CommanderRoute: CommanderRoute,
  FloorPlansRoute: FloorPlansRoute,
  IncidentsRoute: IncidentsRoute,
  OccupancyRoute: OccupancyRoute,
  PersonnelRoute: PersonnelRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  VulnerabilityRoute: VulnerabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
